[package]
name = "wasm-qr"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
image = "0.25.2"
js-sys = "0.3.72"
quircs = "0.10.2"
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.72", features = ["FileReader", "console"] }
